// vue/docs/src/views/Changelog.vue
<template>
  <!--begin::Card-->
  <div class="card">
    <!--begin::Card Body-->
    <div class="card-body p-10 p-lg-15">
      <!--begin::Accordion-->
      <div
        class="accordion accordion-flush accordion-icon-toggle"
        id="kt_accordion_2"
      >
        <!--begin::Item-->
        <div class="mb-5">
          <!--begin::Header-->
          <div
            class="accordion-header py-3 d-flex"
            data-bs-toggle="collapse"
            data-bs-target="#kt_accordion_2_item_13"
          >
            <span class="accordion-icon">
              <span class="svg-icon svg-icon-3">
                <inline-svg src="media/icons/duotune/arrows/arr064.svg" />
              </span>
            </span>
            <h3 class="fs-4 text-gray-800 fw-bold mb-0 ms-4">
              {{ themeName }} v8.0.23 - 20 August, 2021
            </h3>
          </div>
          <!--end::Header-->

          <!--begin::Body-->
          <div
            id="kt_accordion_2_item_13"
            class="fs-6 collapse show ps-10"
            data-bs-parent="#kt_accordion_2"
          >
            <h3 class="fs-6 fw-bolder show mb-1">New:</h3>
            <ul class="py-2">
              <li class="py-2">
                RTL version setup doc.
                <a
                  href="https://preview.keenthemes.com/metronic8/vue/docs/#/rtl"
                  >Preview</a
                >
              </li>
              <li class="py-2">
                Vue Fullcalendar plugin.
                <a
                  href="https://preview.keenthemes.com/metronic8/vue/docs/#/fullcalendar"
                  >Preview</a
                >
              </li>
              <li class="py-2">Vue currency input mask plugin.</li>
              <a
                href="https://preview.keenthemes.com/metronic8/vue/docs/#//vue-currency-input"
                >Preview</a
              >
            </ul>

            <h3 class="fs-6 fw-bolder show mb-1">Update:</h3>
            <ul class="py-2">
              <li class="py-2">
                Migration to new doutune icons set.
                <a
                  href="https://preview.keenthemes.com/metronic8/vue/docs/#/duotune"
                  >Preview</a
                >
              </li>
              <li class="py-2">Migration to new illustrations set.</li>
              <li class="py-2">DrawerComponent improvements.</li>
              <li class="py-2">
                Updated doc overview page.<a
                  href="https://preview.keenthemes.com/metronic8/vue/docs/#/doc-overview"
                  >Preview</a
                >
              </li>
            </ul>

            <h3 class="fs-6 fw-bolder show mb-1">Fix:</h3>
            <ul class="py-2">
              <li class="py-2">
                Added demo 2 vue version.
                <a
                  href="https://preview.keenthemes.com/metronic8/vue/demo2/#/dashboard"
                  >Preview</a
                >
              </li>
              <li class="py-2">
                Added demo 7 vue version.
                <a
                  href="https://preview.keenthemes.com/metronic8/vue/demo3/#/dashboard"
                  >Preview</a
                >
              </li>
              <li class="py-2">Added RTL version webpack script.</li>
            </ul>
          </div>
          <!--end::Body-->
        </div>
        <!--end::Item-->

        <!--begin::Item-->
        <div class="mb-5">
          <!--begin::Header-->
          <div
            class="accordion-header py-3 d-flex collapsed"
            data-bs-toggle="collapse"
            data-bs-target="#kt_accordion_2_item_12"
          >
            <span class="accordion-icon">
              <span class="svg-icon svg-icon-3">
                <inline-svg src="media/icons/duotune/arrows/arr064.svg" />
              </span>
            </span>
            <h3 class="fs-4 text-gray-800 fw-bold mb-0 ms-4">
              {{ themeName }} v8.0.22 - 6 August, 2021
            </h3>
          </div>
          <!--end::Header-->

          <!--begin::Body-->
          <div
            id="kt_accordion_2_item_12"
            class="fs-6 collapse ps-10"
            data-bs-parent="#kt_accordion_2"
          >
            <h3 class="fs-6 fw-bolder show mb-1">New:</h3>
            <ul class="py-2">
              <li class="py-2">
                Added demo 2 vue version.
                <a
                  href="https://preview.keenthemes.com/metronic8/vue/demo2/#/dashboard"
                  >Preview</a
                >
              </li>
              <li class="py-2">
                Added demo 7 vue version.
                <a
                  href="https://preview.keenthemes.com/metronic8/vue/demo3/#/dashboard"
                  >Preview</a
                >
              </li>
              <li class="py-2">Added RTL version webpack script.</li>
            </ul>
          </div>
          <!--end::Body-->
        </div>
        <!--end::Item-->

        <!--begin::Item-->
        <div class="mb-5">
          <!--begin::Header-->
          <div
            class="accordion-header py-3 d-flex collapsed"
            data-bs-toggle="collapse"
            data-bs-target="#kt_accordion_2_item_11"
          >
            <span class="accordion-icon">
              <span class="svg-icon svg-icon-3">
                <inline-svg src="media/icons/duotune/arrows/arr064.svg" />
              </span>
            </span>
            <h3 class="fs-4 text-gray-800 fw-bold mb-0 ms-4">
              {{ themeName }} v8.0.21 - 30 July, 2021
            </h3>
          </div>
          <!--end::Header-->

          <!--begin::Body-->
          <div
            id="kt_accordion_2_item_11"
            class="fs-6 collapse ps-10"
            data-bs-parent="#kt_accordion_2"
          >
            <h3 class="fs-6 fw-bolder show mb-1">New:</h3>
            <ul class="py-2">
              <li class="py-2">
                Dark-mode setup doc.
                <a
                  href="https://preview.keenthemes.com/metronic8/vue/docs/#/dark-mode"
                  >Preview</a
                >
              </li>
              <li class="py-2">
                Internationalization (i18n) setup doc.
                <a
                  href="https://preview.keenthemes.com/metronic8/vue/docs/#/internationalization"
                  >Preview</a
                >
              </li>
              <li class="py-2">
                Vue + Laravel integration doc.
                <a
                  href="https://preview.keenthemes.com/metronic8/vue/docs/#/vue-laravel-integration"
                  >Preview</a
                >
              </li>
            </ul>
            <h3 class="fs-6 fw-bolder show mb-1">Update:</h3>
            <ul class="py-2">
              <li class="py-2">
                Split demo and docs pages into two separate apps.
                <a href="https://preview.keenthemes.com/metronic8/vue/docs/#/"
                  >Preview</a
                >
              </li>
            </ul>
            <h3 class="fs-6 fw-bolder show mb-1">Fixes:</h3>
            <ul class="py-2">
              <li class="py-2">
                Fixed drawer hide then route path is changed.
                <a
                  href="https://preview.keenthemes.com/metronic8/vue/demo1/#/dashboard"
                  >Preview</a
                >
              </li>
            </ul>
          </div>
          <!--end::Body-->
        </div>
        <!--end::Item-->

        <!--begin::Item-->
        <div class="mb-5">
          <!--begin::Header-->
          <div
            class="accordion-header py-3 d-flex collapsed"
            data-bs-toggle="collapse"
            data-bs-target="#kt_accordion_2_item_10"
          >
            <span class="accordion-icon">
              <span class="svg-icon svg-icon-3">
                <inline-svg src="media/icons/duotune/arrows/arr064.svg" />
              </span>
            </span>
            <h3 class="fs-4 text-gray-800 fw-bold mb-0 ms-4">
              {{ themeName }} v8.0.19 - 26 July, 2021
            </h3>
          </div>
          <!--end::Header-->

          <!--begin::Body-->
          <div
            id="kt_accordion_2_item_10"
            class="fs-6 collapse ps-10"
            data-bs-parent="#kt_accordion_2"
          >
            <h3 class="fs-6 fw-bolder show mb-1">Fixes:</h3>
            <ul class="py-2">
              <li class="py-2">
                Fixed content breadcrumb display for content-fluid.
                <a
                  href="https://preview.keenthemes.com/metronic8/vue/demo1/#/dashboard"
                  >Preview</a
                >
              </li>
            </ul>
          </div>
          <!--end::Body-->
        </div>
        <!--end::Item-->

        <!--begin::Item-->
        <div class="mb-5">
          <!--begin::Header-->
          <div
            class="accordion-header py-3 d-flex collapsed"
            data-bs-toggle="collapse"
            data-bs-target="#kt_accordion_2_item_9"
          >
            <span class="accordion-icon">
              <span class="svg-icon svg-icon-3">
                <inline-svg src="media/icons/duotune/arrows/arr064.svg" />
              </span>
            </span>
            <h3 class="fs-4 text-gray-800 fw-bold mb-0 ms-4">
              {{ themeName }} v8.0.18 - 16 July, 2021
            </h3>
          </div>
          <!--end::Header-->

          <!--begin::Body-->
          <div
            id="kt_accordion_2_item_9"
            class="fs-6 collapse ps-10"
            data-bs-parent="#kt_accordion_2"
          >
            <h3 class="fs-6 fw-bolder mb-1">Fixes:</h3>
            <ul class="py-2">
              <li class="py-2">
                Fixed breadcrumb on mobile version.
                <a
                  href="https://preview.keenthemes.com/metronic8/vue/demo1/#/dashboard"
                  >Preview</a
                >
              </li>
            </ul>
          </div>
          <!--end::Body-->
        </div>
        <!--end::Item-->

        <!--begin::Item-->
        <div class="mb-5">
          <!--begin::Header-->
          <div
            class="accordion-header py-3 d-flex collapsed"
            data-bs-toggle="collapse"
            data-bs-target="#kt_accordion_2_item_8"
          >
            <span class="accordion-icon">
              <span class="svg-icon svg-icon-3">
                <inline-svg src="media/icons/duotune/arrows/arr064.svg" />
              </span>
            </span>
            <h3 class="fs-4 text-gray-800 fw-bold mb-0 ms-4">
              {{ themeName }} v8.0.17 - 7 July, 2021
            </h3>
          </div>
          <!--end::Header-->

          <!--begin::Body-->
          <div
            id="kt_accordion_2_item_8"
            class="fs-6 collapse ps-10"
            data-bs-parent="#kt_accordion_2"
          >
            <h3 class="fs-6 fw-bolder mb-1">New:</h3>
            <ul class="py-2">
              <li class="py-2">
                Added general modal pages
                <a
                  href="https://preview.keenthemes.com/metronic8/vue/demo1/#/crafted/pages/profile/activity"
                  >Preview</a
                >
              </li>
            </ul>
            <h3 class="fs-6 fw-bolder mb-1">Fixes:</h3>
            <ul class="py-2">
              <li class="py-2">
                Fixed DrawerMessanger initialization bug
                <a
                  href="https://preview.keenthemes.com/metronic8/vue/demo1/#/apps/chat/drawer-chat"
                  >Preview</a
                >
              </li>
            </ul>
          </div>
          <!--end::Body-->
        </div>
        <!--end::Item-->

        <!--begin::Item-->
        <div class="mb-5">
          <!--begin::Header-->
          <div
            class="accordion-header py-3 d-flex collapsed"
            data-bs-toggle="collapse"
            data-bs-target="#kt_accordion_2_item_7"
          >
            <span class="accordion-icon">
              <span class="svg-icon svg-icon-3">
                <inline-svg src="media/icons/duotune/arrows/arr064.svg" />
              </span>
            </span>
            <h3 class="fs-4 text-gray-800 fw-bold mb-0 ms-4">
              {{ themeName }} v8.0.16 - 28 June, 2021
            </h3>
          </div>
          <!--end::Header-->

          <!--begin::Body-->
          <div
            id="kt_accordion_2_item_7"
            class="fs-6 collapse ps-10"
            data-bs-parent="#kt_accordion_2"
          >
            <h3 class="fs-6 fw-bolder mb-1">New:</h3>
            <ul class="py-2">
              <li class="py-2">
                Added general modal pages
                <ul class="py-2">
                  <li class="py-2">
                    Invite Friends
                    <a
                      href="https://preview.keenthemes.com/metronic8/vue/demo1/#/crafted/modals/general/invite-friends"
                      >Preview</a
                    >
                  </li>
                  <li class="py-2">
                    View Users
                    <a
                      href="https://preview.keenthemes.com/metronic8/vue/demo1/#/crafted/modals/general/view-user"
                      >Preview</a
                    >
                  </li>
                  <li class="py-2">
                    Upgrade Plan
                    <a
                      href="https://preview.keenthemes.com/metronic8/vue/demo1/#/crafted/modals/general/upgrade-plan"
                      >Preview</a
                    >
                  </li>
                  <li class="py-2">
                    Share & Earn
                    <a
                      href="https://preview.keenthemes.com/metronic8/vue/demo1/#/crafted/modals/general/share-and-earn"
                      >Preview</a
                    >
                  </li>
                </ul>
              </li>
              <li class="py-2">
                Added form modal pages
                <ul class="py-2">
                  <li class="py-2">
                    New Targer
                    <a
                      href="https://preview.keenthemes.com/metronic8/vue/demo1/#/crafted/modals/forms/new-target"
                      >Preview</a
                    >
                  </li>
                  <li class="py-2">
                    New Card
                    <a
                      href="https://preview.keenthemes.com/metronic8/vue/demo1/#/crafted/modals/forms/new-card"
                      >Preview</a
                    >
                  </li>
                  <li class="py-2">
                    New Address
                    <a
                      href="https://preview.keenthemes.com/metronic8/vue/demo1/#/crafted/modals/forms/new-address"
                      >Preview</a
                    >
                  </li>
                  <li class="py-2">
                    Create API Key
                    <a
                      href="https://preview.keenthemes.com/metronic8/vue/demo1/#/crafted/modals/forms/create-api-key"
                      >Preview</a
                    >
                  </li>
                </ul>
              </li>
              <li class="py-2">
                Added wizard modal pages
                <ul class="py-2">
                  <li class="py-2">
                    Two Factor Auth
                    <a
                      href="https://preview.keenthemes.com/metronic8/vue/demo1/#/crafted/modals/wizards/two-factor-auth"
                      >Preview</a
                    >
                  </li>
                  <li class="py-2">
                    Create App
                    <a
                      href="https://preview.keenthemes.com/metronic8/vue/demo1/#/crafted/modals/wizards/create-app"
                      >Preview</a
                    >
                  </li>
                  <li class="py-2">
                    Create Account
                    <a
                      href="https://preview.keenthemes.com/metronic8/vue/demo1/#/crafted/modals/wizards/create-account"
                      >Preview</a
                    >
                  </li>
                </ul>
              </li>
            </ul>
          </div>
          <!--end::Body-->
        </div>
        <!--end::Item-->

        <!--begin::Item-->
        <div class="mb-5">
          <!--begin::Header-->
          <div
            class="accordion-header py-3 d-flex collapsed"
            data-bs-toggle="collapse"
            data-bs-target="#kt_accordion_2_item_6"
          >
            <span class="accordion-icon">
              <span class="svg-icon svg-icon-3">
                <inline-svg src="media/icons/duotune/arrows/arr064.svg" />
              </span>
            </span>
            <h3 class="fs-4 text-gray-800 fw-bold mb-0 ms-4">
              {{ themeName }} v8.0.15 - 17 June, 2021
            </h3>
          </div>
          <!--end::Header-->

          <!--begin::Body-->
          <div
            id="kt_accordion_2_item_6"
            class="fs-6 collapse ps-10"
            data-bs-parent="#kt_accordion_2"
          >
            <h3 class="fs-6 fw-bolder mb-1">New:</h3>
            <ul class="py-2">
              <li class="py-2">
                Added widgets pages
                <a
                  href="https://preview.keenthemes.com/metronic8/vue/demo1/#/crafted/widgets/lists"
                  >Preview</a
                >
              </li>
            </ul>
          </div>
          <!--end::Body-->
        </div>
        <!--end::Item-->

        <!--begin::Item-->
        <div class="mb-5">
          <!--begin::Header-->
          <div
            class="accordion-header py-3 d-flex collapsed"
            data-bs-toggle="collapse"
            data-bs-target="#kt_accordion_2_item_5"
          >
            <span class="accordion-icon">
              <span class="svg-icon svg-icon-3">
                <inline-svg src="media/icons/duotune/arrows/arr064.svg" />
              </span>
            </span>
            <h3 class="fs-4 text-gray-800 fw-bold mb-0 ms-4">
              {{ themeName }} v8.0.14 - 4 June, 2021
            </h3>
          </div>
          <!--end::Header-->

          <!--begin::Body-->
          <div
            id="kt_accordion_2_item_5"
            class="fs-6 collapse ps-10"
            data-bs-parent="#kt_accordion_2"
          >
            <h3 class="fs-6 fw-bolder mb-1">New:</h3>
            <ul class="py-2">
              <li class="py-2">
                Added vue-i18n plugin and menu translation example. Update
                languge in profile dropdown.
                <a
                  href="https://preview.keenthemes.com/metronic8/vue/demo1/#/dashboard"
                  >Preview</a
                >
              </li>
            </ul>
          </div>
          <!--end::Body-->
        </div>
        <!--end::Item-->

        <!--begin::Item-->
        <div class="mb-5">
          <!--begin::Header-->
          <div
            class="accordion-header py-3 d-flex collapsed"
            data-bs-toggle="collapse"
            data-bs-target="#kt_accordion_2_item_4"
          >
            <span class="accordion-icon">
              <span class="svg-icon svg-icon-3">
                <inline-svg src="media/icons/duotune/arrows/arr064.svg" />
              </span>
            </span>
            <h3 class="fs-4 text-gray-800 fw-bold mb-0 ms-4">
              {{ themeName }} v8.0.13 - 9 June, 2021
            </h3>
          </div>
          <!--end::Header-->

          <!--begin::Body-->
          <div
            id="kt_accordion_2_item_4"
            class="fs-6 collapse ps-10"
            data-bs-parent="#kt_accordion_2"
          >
            <h3 class="fs-6 fw-bolder mb-1">New:</h3>
            <ul class="py-2">
              <li class="py-2">
                Added private chat page.
                <a
                  href="https://preview.keenthemes.com/metronic8/vue/demo1/#/apps/chat/private-chat"
                  >Preview</a
                >
              </li>
              <li class="py-2">
                Added group chat page.
                <a
                  href="https://preview.keenthemes.com/metronic8/vue/demo1/#/apps/chat/group-chat"
                  >Preview</a
                >
              </li>
              <li class="py-2">
                Added drawer chat page.
                <a
                  href="https://preview.keenthemes.com/metronic8/vue/demo1/#/apps/chat/drawer-chat"
                  >Preview</a
                >
              </li>
            </ul>
          </div>
          <!--end::Body-->
        </div>
        <!--end::Item-->

        <!--begin::Item-->
        <div class="mb-5">
          <!--begin::Header-->
          <div
            class="accordion-header py-3 d-flex collapsed"
            data-bs-toggle="collapse"
            data-bs-target="#kt_accordion_2_item_3"
          >
            <span class="accordion-icon">
              <span class="svg-icon svg-icon-3">
                <inline-svg src="media/icons/duotune/arrows/arr064.svg" />
              </span>
            </span>
            <h3 class="fs-4 text-gray-800 fw-bold mb-0 ms-4">
              {{ themeName }} v8.0.12 - 28 May, 2021
            </h3>
          </div>
          <!--end::Header-->

          <!--begin::Body-->
          <div
            id="kt_accordion_2_item_3"
            class="fs-6 collapse ps-10"
            data-bs-parent="#kt_accordion_2"
          >
            <h3 class="fs-6 fw-bolder mb-1">New:</h3>
            <ul class="py-2">
              <li class="py-2">
                Added wizard demo pages.
                <a
                  href="https://preview.keenthemes.com/metronic8/vue/demo1/#/crafted/pages/wizards/vertical"
                  >Preview</a
                >
              </li>
            </ul>
          </div>
          <!--end::Body-->
        </div>
        <!--end::Item-->

        <!--begin::Item-->
        <div class="mb-5">
          <!--begin::Header-->
          <div
            class="accordion-header py-3 d-flex collapsed"
            data-bs-toggle="collapse"
            data-bs-target="#kt_accordion_2_item_2"
          >
            <span class="accordion-icon">
              <span class="svg-icon svg-icon-3">
                <inline-svg src="media/icons/duotune/arrows/arr064.svg" />
              </span>
            </span>
            <h3 class="fs-4 text-gray-800 fw-bold mb-0 ms-4">
              {{ themeName }} v8.0.11 - 26 May, 2021
            </h3>
          </div>
          <!--end::Header-->

          <!--begin::Body-->
          <div
            id="kt_accordion_2_item_2"
            class="fs-6 collapse ps-10"
            data-bs-parent="#kt_accordion_2"
          >
            <h3 class="fs-6 fw-bolder mb-1">New:</h3>
            <ul class="py-2">
              <li class="py-2">
                Setup theme skeleton doc.
                <a
                  href="https://preview.keenthemes.com/metronic8/vue/demo1/#/documentation/setup-theme-skeleton"
                  >Preview</a
                >
              </li>
            </ul>
            <h3 class="fs-6 fw-bolder mb-1">Update:</h3>
            <ul class="py-2">
              <li class="py-2">
                Updated sign-in form buttons.
                <a
                  href="https://preview.keenthemes.com/metronic8/vue/demo1/#/sign-in"
                  >Preview</a
                >
              </li>
            </ul>
          </div>
          <!--end::Body-->
        </div>
        <!--end::Item-->

        <!--begin::Item-->
        <div class="mb-5">
          <!--begin::Header-->
          <div
            class="accordion-header py-3 d-flex collapsed"
            data-bs-toggle="collapse"
            data-bs-target="#kt_accordion_2_item_1"
          >
            <span class="accordion-icon">
              <span class="svg-icon svg-icon-3">
                <inline-svg src="media/icons/duotune/arrows/arr064.svg" />
              </span>
            </span>
            <h3 class="fs-4 text-gray-800 fw-bold mb-0 ms-4">
              {{ themeName }} v8.0.10 - 21 May, 2021
            </h3>
          </div>
          <!--end::Header-->

          <!--begin::Body-->
          <div
            id="kt_accordion_2_item_1"
            class="fs-6 collapse ps-10"
            data-bs-parent="#kt_accordion_2"
          >
            <ul class="py-2">
              <li class="py-2">Initial release.</li>
            </ul>
          </div>
          <!--end::Body-->
        </div>
        <!--end::Item-->
      </div>
      <!--end::Accordion-->
    </div>
    <!--end::Card Body-->
  </div>
  <!--end::Card-->
</template>

<script lang="ts">
import { defineComponent, onMounted } from "vue";
import { themeName } from "@/core/helpers/documentation";
import { setCurrentPageBreadcrumbs } from "../../../demo1/src/core/helpers/breadcrumb";

export default defineComponent({
  name: "changelog",
  components: {},
  setup() {
    onMounted(() => {
      setCurrentPageBreadcrumbs("Campaigns", ["Getting Started"]);
    });

    return {
      themeName,
    };
  },
});
</script>

// react/docs/src/app/gettings-started/Changelog.tsx
import React from 'react'
import {KTSVG} from '../../_metronic/helpers'

export function Changelog() {
  const {REACT_APP_THEME_NAME, REACT_APP_VERSION} = process.env

  return (
    <>
      <div className='accordion accordion-flush accordion-icon-toggle' id='kt_accordion'>
        <div className='accordion-item mb-5'>
          <div
            className='accordion-header py-3 d-flex'
            data-bs-toggle='collapse'
            data-bs-target='#kt_accordion_body_v8_0_23'
            aria-expanded='true'
          >
            <span className='accordion-icon'>
              <KTSVG
                path='/media/icons/duotune/arrows/arr064.svg'
                className='svg-icon svg-icon-3'
              />
            </span>
            <h3 className='fs-3 text-gray-800 fw-bolder mb-0 ms-4'>
              {REACT_APP_THEME_NAME} {REACT_APP_VERSION} - August 20, 2021
            </h3>
          </div>
          <div
            id='kt_accordion_body_v8_0_23'
            className='fs-6 my-1 py-0 ps-10 collapse show'
            data-bs-parent='#kt_accordion'
          >
            <div className='accordion-body ps-0 pt-0'>
              <div className='mb-5'>
                <h3 className='fs-6 fw-bolder mb-1'>New:</h3>
                <ul className='my-0 py-0'>
                  <li className='py-2'>
                    RTL version setup doc.{' '}
                    <a href='https://preview.keenthemes.com/metronic8/react/demo1-docs/docs/rtl'>
                      Preview
                    </a>
                  </li>
                </ul>
              </div>
              <div className='mb-5'>
                <h3 className='fs-6 fw-bolder mb-1'>Update:</h3>
                <ul className='my-0 py-0'>
                  <li className='py-2'>
                    Migration to new doutone icons set.{' '}
                    <a href='https://preview.keenthemes.com/metronic8/react/demo1-docs/docs/icons/duotune'>
                      Preview
                    </a>
                  </li>
                  <li className='py-2'>Migration to new illustrations set.</li>
                  <li className='py-2'>DrawerComponent improvements.</li>
                </ul>
              </div>
              <div className='mb-5'>
                <h3 className='fs-6 fw-bolder mb-1'>Fixes:</h3>
                <ul className='my-0 py-0'>
                  <li className='py-2'>
                    Duplicated drawer overlay on second DrawerComponent initialization.
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div className='accordion-item mb-5'>
          <div
            className='accordion-header py-3 d-flex collapsed'
            data-bs-toggle='collapse'
            data-bs-target='#kt_accordion_body_v8_0_22'
            aria-expanded='true'
          >
            <span className='accordion-icon'>
              <KTSVG
                path='/media/icons/duotune/arrows/arr064.svg'
                className='svg-icon svg-icon-3'
              />
            </span>
            <h3 className='fs-3 text-gray-800 fw-bolder mb-0 ms-4'>
              {REACT_APP_THEME_NAME} v8.0.22 - August 6, 2021
            </h3>
          </div>
          <div
            id='kt_accordion_body_v8_0_22'
            className='fs-6 my-1 py-0 ps-10 collapse'
            data-bs-parent='#kt_accordion'
          >
            <div className='accordion-body ps-0 pt-0'>
              <div className='mb-5'>
                <h3 className='fs-6 fw-bolder mb-1'>New:</h3>
                <ul className='my-0 py-0'>
                  <li className='py-2'>
                    Added demo2 react version.{' '}
                    <a href='https://preview.keenthemes.com/metronic/react/demo1/dashboard'>
                      Preview
                    </a>
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div className='accordion-item mb-5'>
          <div
            className='accordion-header py-3 d-flex collapsed'
            data-bs-toggle='collapse'
            data-bs-target='#kt_accordion_body_v8_0_21'
            aria-expanded='true'
          >
            <span className='accordion-icon'>
              <KTSVG
                path='/media/icons/duotune/arrows/arr064.svg'
                className='svg-icon svg-icon-3'
              />
            </span>
            <h3 className='fs-3 text-gray-800 fw-bolder mb-0 ms-4'>
              {REACT_APP_THEME_NAME} v8.0.21 - July 30, 2021
            </h3>
          </div>
          <div
            id='kt_accordion_body_v8_0_21'
            className='fs-6 my-1 py-0 ps-10 collapse'
            data-bs-parent='#kt_accordion'
          >
            <div className='accordion-body ps-0 pt-0'>
              <div className='mb-5'>
                <h3 className='fs-6 fw-bolder mb-1'>New:</h3>
                <ul className='my-0 py-0'>
                  <li className='py-2'>
                    Dark mode setup doc.{' '}
                    <a href='https://preview.keenthemes.com/metronic8/react/demo1-docs/docs/dark-mode'>
                      Preview
                    </a>
                  </li>
                </ul>
              </div>
              <div className='mb-5'>
                <h3 className='fs-6 fw-bolder mb-1'>Fix:</h3>
                <ul className='my-0 py-0'>
                  <li className='py-2'>
                    <code className='ms-0'>Error page </code> redirect issue. Now we have page
                    refresh after redirect from Error pages.
                  </li>
                </ul>
              </div>
            </div>
          </div>
        </div>
        <div className='accordion-item mb-5'>
          <div
            className='accordion-header py-3 d-flex collapsed'
            data-bs-toggle='collapse'
            data-bs-target='#kt_accordion_body_v1_0_0'
            aria-expanded='true'
          >
            <span className='accordion-icon'>
              <KTSVG
                path='/media/icons/duotune/arrows/arr064.svg'
                className='svg-icon svg-icon-3'
              />
            </span>
            <h3 className='fs-3 text-gray-800 fw-bolder mb-0 ms-4'>
              {REACT_APP_THEME_NAME} v8.0.19 - July 20, 2021
            </h3>
          </div>
          <div
            id='kt_accordion_body_v1_0_0'
            className='fs-6 my-1 py-0 ps-10 collapse'
            data-bs-parent='#kt_accordion'
          >
            <div className='accordion-body ps-0 pt-0'>
              <ul className='my-0 py-0'>
                <li className='py-2'>Initial release</li>
              </ul>
            </div>
          </div>
        </div>
      </div>
    </>
  )
}
